name: "Send to Allure Docker Service"
description: "Sends allure reports to dockerized server"
author: "unickq"
branding:
  icon: 'upload'  
  color: 'yellow'

inputs:
  allure_results:
    description: "Allure results dir"
    required: false
    default: 'allure-results'
  project_id:
    description: "Project id"
    required: false
    default: 'default'
  auth:
    description: "Security"
    required: false
    default: 'true'
  generate:
    description: "Generate report finish"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/script.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/script.sh ${{ inputs.allure_results }} ${{ inputs.project_id }} ${{ inputs.auth }} ${{ inputs.generate }}
      shell: bash
